pipeline {
    agent any
    tools {
        maven '3.9.6'
    }
    stages {
        stage('Build') {
            steps {
                cmd /c 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                cmd /c 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                cmd /c './jenkins/scripts/deliver.sh'
            }
        }
    }
}
