pipeline {
    agent any
    tools {
        maven '3.9.6'
    }
    stages {
        stage('Build') {
            steps {
                 '"C:\Program Files\Git\bin\sh.exe" mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                "C:\Program Files\Git\bin\sh.exe" 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                "C:\Program Files\Git\bin\sh.exe" './jenkins/scripts/deliver.sh'
            }
        }
    }
}
